import type { Metadata } from "next";
import { Inter, Lato, Mulish } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  display: "swap",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lato.variable} ${mulish.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
