import type { Metadata } from "next";
import { Inter, Lato, Mulish, Syne, Raleway } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";
import MobileNav from "@/components/MobileNav";
import Footer from "@/components/Footer";
import BackToTop from '@/components/BackToTop';

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
  preload: true,
});

const lato = Lato({
  variable: "--font-lato",
  display: "swap",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  preload: true,
});

const mulish = Mulish({
  variable: "--font-mulish",
  display: "swap",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  preload: true,
});

const syne = Syne({
  variable: "--font-syne",
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  preload: true,
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lato.variable} ${mulish.variable} ${syne.variable} ${raleway.variable} bg-[#FFF5F5]`}
      >
        <Topbar />
        <Navbar />
        <MobileNav />
        {children}
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
